export const artists = [
  "!!!",
  "(sandy) alex g",
  "...and you will know us by the trail of dead",
  "2562",
  "a hawk and a hacksaw",
  "a hawk and a hacksaw and the hun hangár ensemble",
  "a minor forest",
  "a sunny day in glasgow",
  "a tribe called quest",
  "a wilhelm scream",
  "a.a. bondy",
  "abe vigoda",
  "abilene",
  "ace of base",
  "active minds",
  "actor",
  "actress",
  "adam harasiewicz",
  "adrian orange",
  "adrianne lenker",
  "against all logic",
  "ahmad jamal quintet",
  "ahmad jamal trio",
  "aidan baker & tim hecker",
  "air",
  "alain bellaïche",
  "alain bellaïche",
  "alan sparhawk",
  "album leaf",
  "alex theory",
  "alfred brendel",
  "algernon cadwallader",
  "ali farka toure",
  "ali farka touré",
  "ali farka touré with ry cooder",
  "alice coltrane",
  "allen toussaint",
  "ambulance ltd",
  "american football",
  "andrea",
  "angelo badalamenti",
  "animal collective",
  "animal liberation orchestra",
  "anthony braxton, milford graves & william parker",
  "antlers",
  "antônio carlos jobim & elis regina",
  "apostle of hustle (feat. the huskys)",
  "apparat",
  "apple",
  "apples in stereo",
  "arcade fire",
  "archers of loaf",
  "architecture in helsinki",
  "aretha franklin",
  "ariel pink's haunted graffiti",
  "armando gallop & steve poindexter",
  "arp",
  "art tatum",
  "astrobrite",
  "ativin",
  "atlas sound",
  "avey tare",
  "avey tare & kria brekken",
  "ayako hotta-lister",
  "azimuth",
  "bailiff & sparhawk",
  "balmorhea",
  "band of horses",
  "bark psychosis",
  "barrington levy",
  "baths",
  "battles",
  "bauhaus",
  "beach fossils",
  "beach house",
  "beak",
  "bear in heaven",
  "beastie boys",
  "beat happening",
  "beck",
  "bedhead",
  "belle & sebastian",
  "belle and sebastian",
  "ben folds",
  "ben folds five",
  "ben frost",
  "beulah",
  "bibio",
  "big bird",
  "big star",
  "big thief",
  "bill callahan",
  "billie holiday",
  "binary star",
  "bird names",
  "bishop allen",
  "black midi",
  "black moth super rainbow",
  "black pyramid",
  "blake mills",
  "blind blake & the royal victoria hotel calypsos",
  "blitzen trapper",
  "blonde redhead",
  "blue cheer",
  "blur",
  "boards of canada",
  "bob dylan",
  "bobby mcferrin",
  "bobby mcferrin & chick corea",
  "bobby wright",
  "body language",
  "bon iver",
  'bonnie "prince" billy',
  "bonobo",
  "bonobo feat. cornelia",
  "bonobo feat. erykah badu",
  "bonobo feat. grey reverend",
  "bonobo feat. szjerdene",
  "boredoms",
  "bottomless pit",
  "braid",
  "brian eno",
  "brian wilson",
  "brightblack morning light",
  "broadcast and the focus group",
  "broken social scene",
  "buddy holly",
  "built to spill",
  "bunzu sounds",
  "burial",
  "burning hearts",
  "busta rhymes",
  "butter 08",
  "c++",
  "calexico",
  "califone",
  "calm down it's monday",
  "calm down, it's monday",
  "calvin johnson",
  "camera obscura",
  "camille saint-saens",
  "can",
  "cap'n jazz",
  "captain beefheart & his magic band",
  "car seat headrest",
  "caribou",
  "cass mccombs",
  "cat power",
  "catatonic youth",
  "cate le bon",
  "cave",
  "cecil taylor",
  "celebration",
  "cfcf",
  "chad vangaalen",
  "charalambides",
  "charles mingus",
  "charley patton",
  "charlie louvin",
  "chick corea",
  "chick corea & béla fleck",
  "chick corea and herbie hancock",
  "chocolate usa",
  "chokebore",
  "chon",
  "christian löffler",
  "christmas island",
  "christopher o'riley",
  "chromatics",
  "chvrches",
  "clark",
  "claudio arrau",
  "claudio arrau, london philharmonic orchestra and eliahu inbal",
  "clem snide",
  "clinic",
  "cloud nothings",
  "codeine",
  "collections of colonies of bees",
  "colophon - vicodin dream",
  "coltrane, john",
  "come",
  "condo fucks",
  "converge",
  "cornelius",
  "count basie",
  "courtney barnett",
  "covet",
  "crazy bald heads",
  "crosby, stills & nash",
  "crosby, stills, nash & young",
  "crystal castles",
  "cursive",
  "cymbals eat guitars",
  "cypress string quartet",
  "d'angelo",
  "d'angelo and the vanguard",
  "d+",
  "daedelus",
  "daft punk",
  "damon & naomi",
  "dan melchior und das menace",
  "danger mouse & daniele luppi",
  "daniel johnston",
  "daphni",
  "darkside",
  "datarock",
  "daughn gibson",
  "dave brubeck",
  "david bazan",
  "david borden",
  "david bowie",
  "david karsten daniels and fight the big bull",
  "dawn of midi",
  "dead moon",
  "deafheaven",
  "death cab for cutie",
  "death vessel",
  "deep magic",
  "deerhoof",
  "deerhunter",
  "delgados, the",
  "delta sleep",
  "demdike stare",
  "depeche mode",
  "destroyer",
  "detective kalita",
  "devo",
  "didier paquette",
  "dimlite",
  "dinosaur jr.",
  "dirty projectors",
  "dirty three",
  "disasterpeace",
  "disco inferno",
  "divine fits",
  "dj jedi",
  "dj koze",
  "do make say think",
  "dodo bird",
  "dodos",
  "dogleg",
  "don caballero",
  "don cabellero",
  "dosh",
  "double leopards",
  "doug martsch",
  "drive like jehu",
  "ducktails",
  "duke ellington",
  "dump",
  "dungen",
  "duran duran",
  "dustin wong",
  "dusty springfield",
  "earl hines & jimmy rushing",
  "earlimart",
  "early day miners",
  "earth",
  "echo & the bunnymen",
  "edit",
  "el michels affair",
  "electrelane",
  "electric six",
  "electric wizard",
  "elevator",
  "elf power",
  "elf power/the amorphous strums/vic chesnutt",
  "elfin saddle",
  "ella fitzgerald and louis armstrong",
  "elliott smith",
  "elton john",
  "eluvium",
  "elvis costello",
  "elvis costello & the attractions",
  "elvis depressedly",
  "elvis presley",
  "eno & hyde",
  "enon",
  "eric copeland",
  "eric's trip",
  "errors",
  "erykah badu",
  "esg",
  "espers",
  "eurythmics",
  "everly brothers",
  "evgeny kissin",
  "explosions in the sky",
  "fats domino",
  "feist",
  "fembots",
  "field music",
  "final fantasy",
  "fire! with jim o'rourke",
  "first aid kit",
  "flaming lips",
  "fleet foxes",
  "floating points",
  "floral",
  "fly pan am",
  "flying",
  "flying lotus",
  "flying saucer attack",
  "foals",
  "folk implosion",
  "fond of tigers",
  "foot ox",
  "forest swords",
  "four tet",
  "foxygen",
  "frances quinlan",
  "frank ocean",
  "franz liszt",
  "fridge",
  "frédéric chopin",
  "fuck buttons",
  "fugazi",
  "fugees",
  "future bible heroes",
  "füxa",
  "gabriela robin",
  "galaxie 500",
  "gallops",
  "gang of four",
  "gary hoffman",
  "gasper lawal",
  "gastr del sol",
  "genius",
  "george gershwin",
  "george harrison",
  "gerard bauer & mike bauer",
  "get back guinozzo",
  "ghostface killah",
  "gifts from enola",
  "girl talk",
  "girlpool",
  "girls",
  "giulio caccini & paul pritchard",
  "glenn branca",
  "glenn gould",
  "glissandro 70",
  "gnarls barkley",
  "god is an astronaut",
  "godspeed you! black emperor",
  "gold panda",
  "golden boots",
  "golden retriever",
  "gov't mule",
  "grackle",
  "grand archives",
  "grandaddy",
  "grandpa boy",
  "grateful dead",
  "great lake swimmers",
  "gregor samsa",
  "grizzly bear",
  "grouper",
  "growing",
  "guards",
  "guided by voices",
  "hall & oates",
  "halo benders",
  "hammock",
  "hanged up",
  "hangedup",
  "harlem",
  "harry belafonte",
  "harry nilsson",
  "harry nilsson/masked alberts orchestra",
  "haruomi hosono",
  "hauschka",
  "heatmiser",
  "hefner",
  "helen callus and philip bush",
  "helios",
  "herbie hancock",
  "here we go magic",
  "high on fire",
  "holden",
  "holy fuck",
  "hood",
  "hoover",
  "hop along",
  "hot chip",
  "how to dress well",
  "howard tate",
  "hundred waters",
  "hush arbors",
  "ida",
  "idaho",
  "idles",
  "iggy & the stooges",
  "iggy and the stooges",
  "ilad",
  "incendiary",
  "indian jewelry",
  "indian summer",
  "interpol",
  "inxs",
  "iron & wine",
  "iron & wine and calexico",
  "iron & wine with calexico",
  "islands",
  "jack white",
  "jaga jazzist",
  "james blake",
  "james carter & cyrus chestnut & ali jackson & reginald veal",
  "james holden",
  "james mercer",
  "james ruskin",
  "japandroids",
  "japanese breakfast",
  "jason lytle",
  "jawbox",
  "jeff buckley",
  "jeff mangum",
  "jeffrey & jack lewis",
  "jens lekman",
  "jerry lee lewis",
  "jessica bailiff",
  "jesu",
  "jib kidder",
  "jim o'rourke",
  "jim o`rourke",
  "joan baez",
  "joan of arc",
  "joe henry",
  "johann johannsson",
  "johann sebastian bach",
  "john arpin",
  "john coltrane",
  "john lennon",
  "john luther adams",
  "john talabot",
  "john vanderslice",
  "john zorn",
  "jon hopkins",
  "jonny greenwood",
  "jonti",
  "joy division",
  "julia jacklin",
  "julie doiron",
  "july skies",
  "june of 44",
  "junior boys",
  "junior senior",
  "justice",
  "justice ",
  "jóhann jóhannsson",
  "kaitlyn aurelia smith",
  "kara-lis coverdale",
  "karate",
  "karen dalton",
  "karl blau",
  "kasi",
  "kavinsky",
  "kavinsky/lovefoxxx",
  "ken nordine",
  "kendrick lamar",
  "kevin drew",
  "kh",
  "khruangbin",
  "kieran hebden & steve reid",
  "kieran hebden|steve reid",
  "killer mike",
  "king khan & bbq show",
  "king khan & the shrines",
  "king krule",
  "king's daughters & sons",
  "kinks, the",
  "kma",
  "kneebody",
  "knots",
  "kourosh yaghmaei",
  "kurt vile",
  "labradford",
  "ladytron",
  "lake",
  "lambchop",
  "laura gibson",
  "lauren laverne",
  "lcd soundsystem",
  "le fly pan am",
  "le tigre",
  "led zeppelin",
  "lederhosen lucil and kid koala",
  "lee hazlewood",
  "legowelt",
  "leonard cohen",
  "les savy fav",
  "lfo",
  "liars",
  "lightships",
  "little richard",
  "little wings",
  "loch lomond",
  "loma prieta",
  "lone",
  "loren connors & jim o'rourke",
  "loren connors & jim o'rourke",
  "loscil",
  "lou barlow & his sentridoh",
  "lou reed",
  "louise johnson",
  "low",
  "low + dirty three",
  "lowercase",
  "lucas reynolds",
  "lucky dragons",
  "ludwig van beethoven",
  "lukas nystrand",
  "luke abbott",
  "luna",
  "lusine",
  "lynx",
  "m. ward",
  "m83",
  "mac demarco",
  "machinedrum",
  "machito",
  "magnolia electric co",
  "magnolia electric co.",
  "major organ and the adding machine",
  "male bonding",
  "malkmus, stephen",
  "manitoba",
  "manu dibango",
  "mark gartman & rivulets",
  "mark guiliana",
  "mark hollis",
  "mark kozelek",
  "mark mothersbaugh",
  "martha argerich",
  "maserati",
  "mastodon",
  "matias aguayo",
  "matthew e. white",
  "maurizio pollini",
  "medeski, martin & wood",
  "melody's echo chamber",
  "memory cassette",
  "memory tapes",
  "menomena",
  "mercury rev",
  "metz",
  "mf doom",
  "michael andrews",
  "michael andrews & gary jules",
  "michael jackson",
  "michel redolfi",
  "microphones",
  "miles davis",
  "mineral",
  "mission of burma",
  "mit",
  "mitch hedberg",
  "mitski",
  "moderat",
  "modern baseball",
  "modest mouse",
  "mogwai",
  "mojave 3",
  "molina & johnson",
  "monobody",
  "montag",
  "moose",
  "mordant music",
  "morphine",
  "motorbikes",
  "mount eerie",
  "moussa doumbia",
  "muddy waters",
  "munir bashir",
  "murcof",
  "mutantes",
  "mutual benefit",
  "my bloody valentine",
  "nada surf",
  "nathan fake",
  "negativland",
  "neil young",
  "neil young and crazy horse",
  "neon indian",
  "neutral milk hotel",
  "nick drake",
  "night control",
  "nikita magaloff",
  "nils frahm",
  "nilsson",
  "nina nastasia",
  "nina simone",
  "nirvana",
  "no. 1 de no. 1",
  "o'riley, christopher",
  "ochre",
  "of montreal",
  "ofo & the black company",
  "oh sees",
  "oingo boingo",
  "okkervil river",
  "ol' dirty bastard",
  "olivia tremor control",
  "omar bashir - munir bashir",
  "oneohtrix point never",
  "optiganally yours",
  "orchestre poly-rythmo de cotonou dahomey",
  "orchestre regional de kayes",
  "oregon painting society",
  "otis redding",
  "ought",
  "paco de lucia",
  "palace music",
  "panda bear",
  "pantha du prince",
  "panther",
  "pants yell!",
  "parquet courts",
  "parts & labor",
  "paul duncan",
  "paul mccartney & wings",
  "paul simon",
  "paul westerberg",
  "pavement",
  "pedro the lion",
  "percussions",
  "perfect pussy",
  "perfume genius",
  "persian",
  "peter jablonski",
  "phantogram",
  "philip glass",
  "philip glass ensemble",
  "philip martin",
  "piano magic",
  "picastro",
  "piebald",
  "pill wonder",
  "pimmon",
  "pinback",
  "pink floyd",
  "pipes you see, pipes you don't",
  "pixies",
  "pole",
  "polvo",
  "polyphia",
  "ponytail",
  "porches.",
  "porn on vinyl",
  "portugal. the man",
  "prefuse 73",
  "presidents of the united states of america",
  "preston school of industry",
  "pretend",
  "prokofiev",
  "protomartyr",
  "pygmy lush",
  "quasi",
  "queen",
  "quito colayco & tony hertz",
  "r.e.m.",
  "rachel's",
  "rachmaninov",
  "radiator hospital",
  "radioactive man",
  "radiohead",
  "rafael toral",
  "randy newman",
  "ratatat",
  "ravi shankar",
  "ravi shankar & philip glass",
  "real estate",
  "red house painters",
  "red rack'em",
  "refused",
  "retribution gospel choir",
  "ricardo villalobos",
  "richard youngs",
  "richie spice",
  "ride",
  "ritual",
  "rivulets",
  "rob clouth",
  "robert vanderbilt",
  "rock plaza central",
  "rodan",
  "rosie thomas",
  "russian circles",
  "röyksopp",
  "sabu",
  "sabu martinez",
  "saloli",
  "salt, peppa and spinderella",
  "sam bauer & gerard bauer",
  "sam prekop",
  "sandro perri",
  "sangkhit prayuk",
  "sarah davachi",
  "satomi saeki",
  "saul williams",
  "scott gilmore",
  "scott walker",
  "sebadoh",
  "sebastian",
  "serge gainsbourg",
  "sergei prokofiev",
  "sergei rachmaninov",
  "sergey prokofiev",
  "set fire to flames",
  "seu jorge",
  "shadow dancer",
  "shellac",
  "shins",
  "shintaro sakamoto",
  "shipping news",
  "shlohmo",
  "should",
  "sigur rós",
  "silkworm",
  "silver apples",
  "silver jews",
  "simon & garfunkel",
  "skee mask",
  "slavic soul party",
  "sleater-kinney",
  "sleeping states",
  "slint",
  "slow mass",
  "slowdive",
  "smog",
  "snoop dogg",
  "snuffaluffagus",
  "soccer mommy",
  "son house",
  "songs: ohia",
  "sonic youth",
  "sonna",
  "sorry bamba",
  "sotsi phromseksan",
  "spacemen 3",
  "spain",
  "sparklehorse",
  "spider bags",
  "spokane",
  "spoon",
  "squarepusher",
  "ss pyramid snake",
  "st. vincent",
  "stamey, chris with yo la tengo",
  "stan getz & joão gilberto",
  "standards",
  "starlight mints",
  "stars of the lid",
  "state faults",
  "stavanger symphony orchestra",
  "stephen malkmus",
  "stephen malkmus & the jicks",
  "stephen malkmus and the jicks",
  "stereolab",
  "steve baker & carmen dave",
  "steve reich",
  "stevie wonder",
  "stl",
  "studio",
  "sufjan stevens",
  "summer cannibals",
  "sun kil moon",
  "sunn o)))",
  "sunny day real estate",
  "super eagles",
  "supertramp",
  "support force",
  "survival knife",
  "sven libaek",
  "swans",
  "swearin'",
  "sweet & innocent",
  "swell maps",
  "sylvan esso",
  "t.s. monk",
  "talk normal",
  "talk talk",
  "talking heads",
  "tall dwarfs",
  "tame impala",
  "tarentel",
  "tears for fears",
  "ted leo & the pharmacists",
  "ted leo and the pharmacists",
  "television",
  "terry riley",
  "texas is the reason",
  "thanksgiving",
  "that dog.",
  "the acid",
  "the aislers set",
  "the album leaf",
  "the american analog set",
  "the animal spirits",
  "the antlers",
  "the apples in stereo",
  "the arcade fire",
  "the avalanches",
  "the beach boys",
  "the beastie boys",
  "the beatles",
  "the besnard lakes",
  "the beta band",
  "the black-eyed snakes",
  "the books",
  "the brian jonestown massacre",
  "the broken family band",
  "the cars",
  "the church",
  "the clash",
  "the claudia quintet",
  "the collapsible mammals",
  "the dave brubeck quartet",
  "the dead texan",
  "the defaulters",
  "the delgados",
  "the dismemberment plan",
  "the dodos",
  "the drift",
  "the essex green",
  "the evens",
  "the field",
  "the firebird band",
  "the flaming lips",
  "the for carnation",
  "the french kicks",
  "the fresh & onlys",
  "the gloria record",
  "the halo benders",
  "the handsome family",
  "the happy hollows",
  "the haxan cloak",
  "the headhunters",
  "the helio sequence",
  "the hold steady",
  "the inhabitants",
  "the innocence mission",
  "the jackson 5",
  "the jesus lizard",
  "the kinks",
  "the legends",
  "the louvin brothers",
  "the mamas and the papas",
  "the mercury program",
  "the meters",
  "the microphones",
  "the minus 5",
  "the misfits",
  "the mountain goats",
  "the nashville teens",
  "the national philharmonic orchestra and richard bonynge",
  "the new pornographers",
  "the new year",
  "the notwist",
  "the ocean floor",
  "the olivia tremor control",
  "the one am radio",
  "the pains of being pure at hea",
  "the pains of being pure at heart",
  "the promise ring",
  "the rapture",
  "the rationals",
  "the rentals",
  "the rivingtons",
  "the rolling stones",
  "the sea and cake",
  "the shaggs",
  "the shaky hands",
  "the shins",
  "the smiths",
  "the soft pink truth",
  "the starlight mints",
  "the stone roses",
  "the stooges",
  "the sunshine fix",
  "the sureshot symphony",
  "the thermals",
  "the unicorns",
  "the velvet teen",
  "the velvet underground",
  "the walkmen",
  "the weakerthans",
  "the white stripes",
  "the who",
  "the wind-up bird",
  "the wrens",
  "the zombies",
  "thee oh sees",
  "thee silver mt. zion memorial orchestra",
  "thelonious monk",
  "thelonious monk quintet",
  "thelonious monk septet",
  "thermals",
  "these new puritans",
  "thingy",
  "this heat",
  "this will destroy you",
  "thom yorke",
  "thundercat",
  "thurston moore",
  "tigran hamasyan",
  "tim hecker",
  "tipper",
  "toadies",
  "tobacco",
  "todd terje",
  "todd terje & the olsens",
  "tom waits",
  "tortoise",
  "toru takemitsu",
  "toshimaru nakamura",
  "townes van zandt",
  "tune-yards",
  "tunji oyelana and the benders",
  "tunng",
  "turing machine",
  "tv on the radio",
  "ty segall",
  "tyondai braxton",
  "u.s. girls",
  "unknown mortal orchestra",
  "unrest",
  "unwound",
  "ursula bogner",
  "valley of the giants",
  "velvet underground",
  "vic chesnutt",
  "vijay iyer",
  "viktor vaughn",
  "villain accelerate",
  "vince guaraldi",
  "vince guaraldi trio",
  "violent femmes",
  "viva voce",
  "vivian girls",
  "vladimir horowitz",
  "volcano choir",
  "voxtrot",
  "vulfpeck",
  "walls",
  "walt disney productions",
  "wavves",
  "wavvves",
  "weakerthans, the",
  "weezer",
  "weird tapes",
  "white lung",
  "white rainbow",
  "white stripes",
  "whitney",
  "wilco",
  "wild nothing",
  "william basinski",
  "william onyeabor",
  "willie brown",
  "willits + sakamoto",
  "windows 96",
  "windy & carl",
  "wire",
  "wk7",
  "wolf parade",
  "wolfgang mozart",
  "women",
  "woods",
  "worriers",
  "wu-tang clan",
  "yacht",
  "yann tiersen",
  "years",
  "yes",
  "yo la tengo",
  "yo-yo ma & bobby mcferrin",
  "yo-yo ma, chris thile & edgar meyer",
  "young jesus",
  "youngstar (musical mob)",
  "zammuto",
];
